name: Hello World CI

on:
  push:
    branches: [ main, master ] # Triggers the workflow on pushes to the main or master branch

jobs:
  build:
    runs-on: ubuntu-latest # Specifies the operating system for the job

    steps:
    - uses: actions/checkout@v4 # Checks out your repository code
      with:
        fetch-depth: 0 # Optional: Fetches all history for all branches and tags

    - name: Say Hello World
      run: echo "Hello, world!" # Executes a shell command to print "Hello, world!"
